### ISSUE TITLE
Zmote no more compatible with HA 2022.2

### ISSUE THREAD

**Issue by manu3b1** [divanikus/zmote#2]
Hi,
With HA 2022.02, zmote device is no more loaded.
Need to correct this warning seen on previous releases:

`2022-02-05 14:30:58 WARNING (MainThread) [homeassistant.components.remote] RemoteDevice is deprecated, modify Zmote2IRRemote to extend RemoteEntity`

Proposed patch:
`class Zmote2IRRemote(remote.RemoteEntity):`

Tested successfully.
Thx.

**Comment by divanikus** [comment]
Fixed. Thanks
